POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "username": "khai.ng81",
    "email": "louiswilliam.personal@gmail.com",
    "password": "Khongnho123"
}

###

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "louiswilliam@gmail.com",
    "password": "Khongnho123"
}